name: Cross-platform Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Run xtask bundle for Windows
        run: cargo xtask bundle oxide_plate --release --target x86_64-pc-windows-gnu

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v3
        with:
          name: windows-bundle
          path: target/bundled

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Native build for macOS
        run: cargo build --release

      - name: Run xtask bundle for macOS
        run: cargo xtask bundle oxide_plate --release

      - name: Upload artifact (macOS)
        uses: actions/upload-artifact@v3
        with:
          name: macos-bundle
          path: target/bundled

  release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
